Feature/local development spa
Skatteetaten/aurora-konsoll pull request #164
Opened 2021-11-26 13:08 UTC by stromland

2021-11-29 11:32 UTC, mikand13 requested changes
Går på overordnet sammenheng med aurora-konsoll-spa

2021-11-29 11:32 UTC, mikand13 commented on src/index.tsx
>    const configOrError = await fetchConfiguration();
Hvorfor ikke bare sende inn config direkte her? Ingen grunn til å ha et config endpoint som uansett serves av root. Dette er jo bare local dev uansett

2021-11-29 11:57 UTC, martinrodland commented on src/web/components/ErrorBoundary/ErrorBoundary.tsx
> +import { IErrors, IAppError } from 'web/models//errors';
Ser det er en del plasser det er dobbel brukt dobbel slash på `models//` og `utils//`. Usikker på om det gjør noe at det er dobbel slash.

2021-11-29 14:05 UTC, stromland commented on src/api/server.ts
> +app.get('/api/config', (req, res) => {
Da synes dette burde ligge her og fjerne det fra root. Siden root ikke har noe forhold til denne konfigurasjonen. Hvis storyteller skjermbildet er avhengig av noen av disse konfigurasjonene så synes jeg det er bedre å duplisere dem i storyteller for å unngå harde koblinger og ekstra kunnskap om hva som brukes hvor.

2021-11-29 14:07 UTC, stromland commented on src/web/components/ErrorBoundary/ErrorBoundary.tsx
> +import { IErrors, IAppError } from 'web/models//errors';
Ser ikke ut som det har gjort noe, men det bør fikses. Jeg skal rydde opp.

2021-11-30 12:39 UTC, mikand13 commented on src/api/server.ts
> +app.get('/api/config', (req, res) => {
Ja, det gir mening, med mindre man har tenkt til å dele opp konsollet mer. Da gir det ikke mening å ha det i en sub-app, da det er den generelle konfigurasjonen til konsollet. Konsollet er jo nå egentlig root.

Om du ønsker å ta config i den sub-appen, så må du endre root så den forwarder configet kallet, .iom det er den som mottar config kallet i sitt api i routen.

2021-12-06 08:22 UTC, martinrodland commented
@stromland Ser bygget feiler på install, men hvis du bumper designsystem versjonen så skal det bygge

2021-12-06 11:15 UTC, martinrodland approved these changes

2021-12-07 12:46 UTC, mikand13 approved these changes

2021-12-07 13:45 UTC, merged